//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS3AudioBot.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TS3AudioBot.Localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string cmd_add_help {
            get {
                return ResourceManager.GetString("cmd_add_help", resourceCulture);
            }
        }
        
        internal static string cmd_api_token_help {
            get {
                return ResourceManager.GetString("cmd_api_token_help", resourceCulture);
            }
        }
        
        internal static string cmd_bot_commander_help {
            get {
                return ResourceManager.GetString("cmd_bot_commander_help", resourceCulture);
            }
        }
        
        internal static string cmd_bot_commander_on_help {
            get {
                return ResourceManager.GetString("cmd_bot_commander_on_help", resourceCulture);
            }
        }
        
        internal static string cmd_bot_commander_off_help {
            get {
                return ResourceManager.GetString("cmd_bot_commander_off_help", resourceCulture);
            }
        }
        
        internal static string cmd_bot_come_help {
            get {
                return ResourceManager.GetString("cmd_bot_come_help", resourceCulture);
            }
        }
        
        internal static string cmd_bot_info_help {
            get {
                return ResourceManager.GetString("cmd_bot_info_help", resourceCulture);
            }
        }
        
        internal static string cmd_bot_info_id_help {
            get {
                return ResourceManager.GetString("cmd_bot_info_id_help", resourceCulture);
            }
        }
        
        internal static string cmd_bot_list_help {
            get {
                return ResourceManager.GetString("cmd_bot_list_help", resourceCulture);
            }
        }
        
        internal static string cmd_bot_move_help {
            get {
                return ResourceManager.GetString("cmd_bot_move_help", resourceCulture);
            }
        }
        
        internal static string cmd_bot_name_help {
            get {
                return ResourceManager.GetString("cmd_bot_name_help", resourceCulture);
            }
        }
        
        internal static string cmd_bot_badges_help {
            get {
                return ResourceManager.GetString("cmd_bot_badges_help", resourceCulture);
            }
        }
        
        internal static string cmd_bot_setup_help {
            get {
                return ResourceManager.GetString("cmd_bot_setup_help", resourceCulture);
            }
        }
        
        internal static string cmd_bot_use_help {
            get {
                return ResourceManager.GetString("cmd_bot_use_help", resourceCulture);
            }
        }
        
        internal static string cmd_clear_help {
            get {
                return ResourceManager.GetString("cmd_clear_help", resourceCulture);
            }
        }
        
        internal static string cmd_bot_disconnect_help {
            get {
                return ResourceManager.GetString("cmd_bot_disconnect_help", resourceCulture);
            }
        }
        
        internal static string cmd_eval_help {
            get {
                return ResourceManager.GetString("cmd_eval_help", resourceCulture);
            }
        }
        
        internal static string cmd_getmy_id_help {
            get {
                return ResourceManager.GetString("cmd_getmy_id_help", resourceCulture);
            }
        }
        
        internal static string cmd_getmy_uid_help {
            get {
                return ResourceManager.GetString("cmd_getmy_uid_help", resourceCulture);
            }
        }
        
        internal static string cmd_getmy_name_help {
            get {
                return ResourceManager.GetString("cmd_getmy_name_help", resourceCulture);
            }
        }
        
        internal static string cmd_getmy_dbid_help {
            get {
                return ResourceManager.GetString("cmd_getmy_dbid_help", resourceCulture);
            }
        }
        
        internal static string cmd_getmy_channel_help {
            get {
                return ResourceManager.GetString("cmd_getmy_channel_help", resourceCulture);
            }
        }
        
        internal static string cmd_getmy_all_help {
            get {
                return ResourceManager.GetString("cmd_getmy_all_help", resourceCulture);
            }
        }
        
        internal static string cmd_getuser_uid_byid_help {
            get {
                return ResourceManager.GetString("cmd_getuser_uid_byid_help", resourceCulture);
            }
        }
        
        internal static string cmd_getuser_name_byid_help {
            get {
                return ResourceManager.GetString("cmd_getuser_name_byid_help", resourceCulture);
            }
        }
        
        internal static string cmd_getuser_dbid_byid_help {
            get {
                return ResourceManager.GetString("cmd_getuser_dbid_byid_help", resourceCulture);
            }
        }
        
        internal static string cmd_getuser_channel_byid_help {
            get {
                return ResourceManager.GetString("cmd_getuser_channel_byid_help", resourceCulture);
            }
        }
        
        internal static string cmd_getuser_all_byid_help {
            get {
                return ResourceManager.GetString("cmd_getuser_all_byid_help", resourceCulture);
            }
        }
        
        internal static string cmd_getuser_id_byname_help {
            get {
                return ResourceManager.GetString("cmd_getuser_id_byname_help", resourceCulture);
            }
        }
        
        internal static string cmd_getuser_all_byname_help {
            get {
                return ResourceManager.GetString("cmd_getuser_all_byname_help", resourceCulture);
            }
        }
        
        internal static string cmd_getuser_name_bydbid_help {
            get {
                return ResourceManager.GetString("cmd_getuser_name_bydbid_help", resourceCulture);
            }
        }
        
        internal static string cmd_getuser_uid_bydbid_help {
            get {
                return ResourceManager.GetString("cmd_getuser_uid_bydbid_help", resourceCulture);
            }
        }
        
        internal static string cmd_help_help {
            get {
                return ResourceManager.GetString("cmd_help_help", resourceCulture);
            }
        }
        
        internal static string cmd_history_add_help {
            get {
                return ResourceManager.GetString("cmd_history_add_help", resourceCulture);
            }
        }
        
        internal static string cmd_history_clean_help {
            get {
                return ResourceManager.GetString("cmd_history_clean_help", resourceCulture);
            }
        }
        
        internal static string cmd_history_delete_help {
            get {
                return ResourceManager.GetString("cmd_history_delete_help", resourceCulture);
            }
        }
        
        internal static string cmd_history_from_help {
            get {
                return ResourceManager.GetString("cmd_history_from_help", resourceCulture);
            }
        }
        
        internal static string cmd_history_id_uint_help {
            get {
                return ResourceManager.GetString("cmd_history_id_uint_help", resourceCulture);
            }
        }
        
        internal static string cmd_history_id_string_help {
            get {
                return ResourceManager.GetString("cmd_history_id_string_help", resourceCulture);
            }
        }
        
        internal static string cmd_history_last_int_help {
            get {
                return ResourceManager.GetString("cmd_history_last_int_help", resourceCulture);
            }
        }
        
        internal static string cmd_history_last_help {
            get {
                return ResourceManager.GetString("cmd_history_last_help", resourceCulture);
            }
        }
        
        internal static string cmd_history_play_help {
            get {
                return ResourceManager.GetString("cmd_history_play_help", resourceCulture);
            }
        }
        
        internal static string cmd_history_rename_help {
            get {
                return ResourceManager.GetString("cmd_history_rename_help", resourceCulture);
            }
        }
        
        internal static string cmd_history_till_DateTime_help {
            get {
                return ResourceManager.GetString("cmd_history_till_DateTime_help", resourceCulture);
            }
        }
        
        internal static string cmd_history_till_string_help {
            get {
                return ResourceManager.GetString("cmd_history_till_string_help", resourceCulture);
            }
        }
        
        internal static string cmd_history_title_help {
            get {
                return ResourceManager.GetString("cmd_history_title_help", resourceCulture);
            }
        }
        
        internal static string cmd_json_merge_help {
            get {
                return ResourceManager.GetString("cmd_json_merge_help", resourceCulture);
            }
        }
        
        internal static string cmd_kickme_help {
            get {
                return ResourceManager.GetString("cmd_kickme_help", resourceCulture);
            }
        }
        
        internal static string cmd_link_help {
            get {
                return ResourceManager.GetString("cmd_link_help", resourceCulture);
            }
        }
        
        internal static string cmd_list_add_help {
            get {
                return ResourceManager.GetString("cmd_list_add_help", resourceCulture);
            }
        }
        
        internal static string cmd_list_clear_help {
            get {
                return ResourceManager.GetString("cmd_list_clear_help", resourceCulture);
            }
        }
        
        internal static string cmd_list_delete_help {
            get {
                return ResourceManager.GetString("cmd_list_delete_help", resourceCulture);
            }
        }
        
        internal static string cmd_list_get_help {
            get {
                return ResourceManager.GetString("cmd_list_get_help", resourceCulture);
            }
        }
        
        internal static string cmd_list_item_move_help {
            get {
                return ResourceManager.GetString("cmd_list_item_move_help", resourceCulture);
            }
        }
        
        internal static string cmd_list_item_delete_help {
            get {
                return ResourceManager.GetString("cmd_list_item_delete_help", resourceCulture);
            }
        }
        
        internal static string cmd_list_list_help {
            get {
                return ResourceManager.GetString("cmd_list_list_help", resourceCulture);
            }
        }
        
        internal static string cmd_list_load_help {
            get {
                return ResourceManager.GetString("cmd_list_load_help", resourceCulture);
            }
        }
        
        internal static string cmd_list_merge_help {
            get {
                return ResourceManager.GetString("cmd_list_merge_help", resourceCulture);
            }
        }
        
        internal static string cmd_list_name_help {
            get {
                return ResourceManager.GetString("cmd_list_name_help", resourceCulture);
            }
        }
        
        internal static string cmd_list_play_help {
            get {
                return ResourceManager.GetString("cmd_list_play_help", resourceCulture);
            }
        }
        
        internal static string cmd_list_queue_help {
            get {
                return ResourceManager.GetString("cmd_list_queue_help", resourceCulture);
            }
        }
        
        internal static string cmd_list_save_help {
            get {
                return ResourceManager.GetString("cmd_list_save_help", resourceCulture);
            }
        }
        
        internal static string cmd_list_show_help {
            get {
                return ResourceManager.GetString("cmd_list_show_help", resourceCulture);
            }
        }
        
        internal static string cmd_next_help {
            get {
                return ResourceManager.GetString("cmd_next_help", resourceCulture);
            }
        }
        
        internal static string cmd_pm_help {
            get {
                return ResourceManager.GetString("cmd_pm_help", resourceCulture);
            }
        }
        
        internal static string cmd_parse_command_help {
            get {
                return ResourceManager.GetString("cmd_parse_command_help", resourceCulture);
            }
        }
        
        internal static string cmd_pause_help {
            get {
                return ResourceManager.GetString("cmd_pause_help", resourceCulture);
            }
        }
        
        internal static string cmd_play_help {
            get {
                return ResourceManager.GetString("cmd_play_help", resourceCulture);
            }
        }
        
        internal static string cmd_plugin_list_help {
            get {
                return ResourceManager.GetString("cmd_plugin_list_help", resourceCulture);
            }
        }
        
        internal static string cmd_plugin_unload_help {
            get {
                return ResourceManager.GetString("cmd_plugin_unload_help", resourceCulture);
            }
        }
        
        internal static string cmd_plugin_load_help {
            get {
                return ResourceManager.GetString("cmd_plugin_load_help", resourceCulture);
            }
        }
        
        internal static string cmd_previous_help {
            get {
                return ResourceManager.GetString("cmd_previous_help", resourceCulture);
            }
        }
        
        internal static string cmd_print_help {
            get {
                return ResourceManager.GetString("cmd_print_help", resourceCulture);
            }
        }
        
        internal static string cmd_quit_help {
            get {
                return ResourceManager.GetString("cmd_quit_help", resourceCulture);
            }
        }
        
        internal static string cmd_quiz_help {
            get {
                return ResourceManager.GetString("cmd_quiz_help", resourceCulture);
            }
        }
        
        internal static string cmd_quiz_on_help {
            get {
                return ResourceManager.GetString("cmd_quiz_on_help", resourceCulture);
            }
        }
        
        internal static string cmd_quiz_off_help {
            get {
                return ResourceManager.GetString("cmd_quiz_off_help", resourceCulture);
            }
        }
        
        internal static string cmd_random_help {
            get {
                return ResourceManager.GetString("cmd_random_help", resourceCulture);
            }
        }
        
        internal static string cmd_random_on_help {
            get {
                return ResourceManager.GetString("cmd_random_on_help", resourceCulture);
            }
        }
        
        internal static string cmd_random_off_help {
            get {
                return ResourceManager.GetString("cmd_random_off_help", resourceCulture);
            }
        }
        
        internal static string cmd_random_seed_help {
            get {
                return ResourceManager.GetString("cmd_random_seed_help", resourceCulture);
            }
        }
        
        internal static string cmd_random_seed_string_help {
            get {
                return ResourceManager.GetString("cmd_random_seed_string_help", resourceCulture);
            }
        }
        
        internal static string cmd_random_seed_int_help {
            get {
                return ResourceManager.GetString("cmd_random_seed_int_help", resourceCulture);
            }
        }
        
        internal static string cmd_repeat_help {
            get {
                return ResourceManager.GetString("cmd_repeat_help", resourceCulture);
            }
        }
        
        internal static string cmd_repeat_one_help {
            get {
                return ResourceManager.GetString("cmd_repeat_one_help", resourceCulture);
            }
        }
        
        internal static string cmd_repeat_off_help {
            get {
                return ResourceManager.GetString("cmd_repeat_off_help", resourceCulture);
            }
        }
        
        internal static string cmd_rights_can_help {
            get {
                return ResourceManager.GetString("cmd_rights_can_help", resourceCulture);
            }
        }
        
        internal static string cmd_rights_reload_help {
            get {
                return ResourceManager.GetString("cmd_rights_reload_help", resourceCulture);
            }
        }
        
        internal static string cmd_rng_help {
            get {
                return ResourceManager.GetString("cmd_rng_help", resourceCulture);
            }
        }
        
        internal static string cmd_seek_help {
            get {
                return ResourceManager.GetString("cmd_seek_help", resourceCulture);
            }
        }
        
        internal static string cmd_song_help {
            get {
                return ResourceManager.GetString("cmd_song_help", resourceCulture);
            }
        }
        
        internal static string cmd_stop_help {
            get {
                return ResourceManager.GetString("cmd_stop_help", resourceCulture);
            }
        }
        
        internal static string cmd_subscribe_help {
            get {
                return ResourceManager.GetString("cmd_subscribe_help", resourceCulture);
            }
        }
        
        internal static string cmd_subscribe_tempchannel_help {
            get {
                return ResourceManager.GetString("cmd_subscribe_tempchannel_help", resourceCulture);
            }
        }
        
        internal static string cmd_subscribe_channel_help {
            get {
                return ResourceManager.GetString("cmd_subscribe_channel_help", resourceCulture);
            }
        }
        
        internal static string cmd_take_help {
            get {
                return ResourceManager.GetString("cmd_take_help", resourceCulture);
            }
        }
        
        internal static string cmd_unsubscribe_help {
            get {
                return ResourceManager.GetString("cmd_unsubscribe_help", resourceCulture);
            }
        }
        
        internal static string cmd_unsubscribe_channel_help {
            get {
                return ResourceManager.GetString("cmd_unsubscribe_channel_help", resourceCulture);
            }
        }
        
        internal static string cmd_unsubscribe_temporary_help {
            get {
                return ResourceManager.GetString("cmd_unsubscribe_temporary_help", resourceCulture);
            }
        }
        
        internal static string cmd_version_help {
            get {
                return ResourceManager.GetString("cmd_version_help", resourceCulture);
            }
        }
        
        internal static string cmd_volume_help {
            get {
                return ResourceManager.GetString("cmd_volume_help", resourceCulture);
            }
        }
        
        internal static string cmd_whisper_all_help {
            get {
                return ResourceManager.GetString("cmd_whisper_all_help", resourceCulture);
            }
        }
        
        internal static string cmd_whisper_group_help {
            get {
                return ResourceManager.GetString("cmd_whisper_group_help", resourceCulture);
            }
        }
        
        internal static string cmd_whisper_list_help {
            get {
                return ResourceManager.GetString("cmd_whisper_list_help", resourceCulture);
            }
        }
        
        internal static string cmd_whisper_off_help {
            get {
                return ResourceManager.GetString("cmd_whisper_off_help", resourceCulture);
            }
        }
        
        internal static string cmd_whisper_subscription_help {
            get {
                return ResourceManager.GetString("cmd_whisper_subscription_help", resourceCulture);
            }
        }
        
        internal static string cmd_xecute_help {
            get {
                return ResourceManager.GetString("cmd_xecute_help", resourceCulture);
            }
        }
        
        internal static string cmd_help_error_ambiguous_command {
            get {
                return ResourceManager.GetString("cmd_help_error_ambiguous_command", resourceCulture);
            }
        }
        
        internal static string cmd_help_error_no_further_subfunctions {
            get {
                return ResourceManager.GetString("cmd_help_error_no_further_subfunctions", resourceCulture);
            }
        }
        
        internal static string cmd_help_error_no_matching_command {
            get {
                return ResourceManager.GetString("cmd_help_error_no_matching_command", resourceCulture);
            }
        }
        
        internal static string cmd_help_error_unknown_error {
            get {
                return ResourceManager.GetString("cmd_help_error_unknown_error", resourceCulture);
            }
        }
        
        internal static string cmd_help_header {
            get {
                return ResourceManager.GetString("cmd_help_header", resourceCulture);
            }
        }
        
        internal static string cmd_help_info_contains_subfunctions {
            get {
                return ResourceManager.GetString("cmd_help_info_contains_subfunctions", resourceCulture);
            }
        }
        
        internal static string cmd_history_clean_confirm_clean {
            get {
                return ResourceManager.GetString("cmd_history_clean_confirm_clean", resourceCulture);
            }
        }
        
        internal static string cmd_history_clean_removedefective_confirm_clean {
            get {
                return ResourceManager.GetString("cmd_history_clean_removedefective_confirm_clean", resourceCulture);
            }
        }
        
        internal static string cmd_history_delete_confirm {
            get {
                return ResourceManager.GetString("cmd_history_delete_confirm", resourceCulture);
            }
        }
        
        internal static string cmd_history_id_last {
            get {
                return ResourceManager.GetString("cmd_history_id_last", resourceCulture);
            }
        }
        
        internal static string cmd_history_id_next {
            get {
                return ResourceManager.GetString("cmd_history_id_next", resourceCulture);
            }
        }
        
        internal static string cmd_history_last_is_empty {
            get {
                return ResourceManager.GetString("cmd_history_last_is_empty", resourceCulture);
            }
        }
        
        internal static string cmd_history_rename_invalid_name {
            get {
                return ResourceManager.GetString("cmd_history_rename_invalid_name", resourceCulture);
            }
        }
        
        internal static string cmd_if_unknown_operator {
            get {
                return ResourceManager.GetString("cmd_if_unknown_operator", resourceCulture);
            }
        }
        
        internal static string cmd_kickme_missing_permission {
            get {
                return ResourceManager.GetString("cmd_kickme_missing_permission", resourceCulture);
            }
        }
        
        internal static string cmd_list_delete_cannot_delete_others_playlist {
            get {
                return ResourceManager.GetString("cmd_list_delete_cannot_delete_others_playlist", resourceCulture);
            }
        }
        
        internal static string cmd_list_delete_confirm {
            get {
                return ResourceManager.GetString("cmd_list_delete_confirm", resourceCulture);
            }
        }
        
        internal static string cmd_list_load_response {
            get {
                return ResourceManager.GetString("cmd_list_load_response", resourceCulture);
            }
        }
        
        internal static string cmd_info_header {
            get {
                return ResourceManager.GetString("cmd_info_header", resourceCulture);
            }
        }
        
        internal static string cmd_list_show_header {
            get {
                return ResourceManager.GetString("cmd_list_show_header", resourceCulture);
            }
        }
        
        internal static string cmd_list_show_header_modifiable {
            get {
                return ResourceManager.GetString("cmd_list_show_header_modifiable", resourceCulture);
            }
        }
        
        internal static string cmd_list_protect {
            get {
                return ResourceManager.GetString("cmd_list_protect", resourceCulture);
            }
        }
        
        internal static string cmd_list_unprotect {
            get {
                return ResourceManager.GetString("cmd_list_unprotect", resourceCulture);
            }
        }
        
        internal static string cmd_pm_hi {
            get {
                return ResourceManager.GetString("cmd_pm_hi", resourceCulture);
            }
        }
        
        internal static string cmd_quit_confirm {
            get {
                return ResourceManager.GetString("cmd_quit_confirm", resourceCulture);
            }
        }
        
        internal static string cmd_quiz_off_no_cheating {
            get {
                return ResourceManager.GetString("cmd_quiz_off_no_cheating", resourceCulture);
            }
        }
        
        internal static string cmd_random_seed_only_letters_allowed {
            get {
                return ResourceManager.GetString("cmd_random_seed_only_letters_allowed", resourceCulture);
            }
        }
        
        internal static string cmd_rights_reload_error_parsing_file {
            get {
                return ResourceManager.GetString("cmd_rights_reload_error_parsing_file", resourceCulture);
            }
        }
        
        internal static string cmd_rng_value_must_be_positive {
            get {
                return ResourceManager.GetString("cmd_rng_value_must_be_positive", resourceCulture);
            }
        }
        
        internal static string cmd_seek_invalid_format {
            get {
                return ResourceManager.GetString("cmd_seek_invalid_format", resourceCulture);
            }
        }
        
        internal static string cmd_seek_out_of_range {
            get {
                return ResourceManager.GetString("cmd_seek_out_of_range", resourceCulture);
            }
        }
        
        internal static string cmd_settings_empty_usage {
            get {
                return ResourceManager.GetString("cmd_settings_empty_usage", resourceCulture);
            }
        }
        
        internal static string error_config_multiple_keys_found {
            get {
                return ResourceManager.GetString("error_config_multiple_keys_found", resourceCulture);
            }
        }
        
        internal static string error_config_no_key_found {
            get {
                return ResourceManager.GetString("error_config_no_key_found", resourceCulture);
            }
        }
        
        internal static string cmd_take_not_enough_arguements {
            get {
                return ResourceManager.GetString("cmd_take_not_enough_arguements", resourceCulture);
            }
        }
        
        internal static string cmd_volume_current {
            get {
                return ResourceManager.GetString("cmd_volume_current", resourceCulture);
            }
        }
        
        internal static string cmd_volume_high_volume_confirm {
            get {
                return ResourceManager.GetString("cmd_volume_high_volume_confirm", resourceCulture);
            }
        }
        
        internal static string cmd_volume_is_limited {
            get {
                return ResourceManager.GetString("cmd_volume_is_limited", resourceCulture);
            }
        }
        
        internal static string cmd_volume_missing_high_volume_permission {
            get {
                return ResourceManager.GetString("cmd_volume_missing_high_volume_permission", resourceCulture);
            }
        }
        
        internal static string cmd_volume_parse_error {
            get {
                return ResourceManager.GetString("cmd_volume_parse_error", resourceCulture);
            }
        }
        
        internal static string cmd_whisper_group_missing_target {
            get {
                return ResourceManager.GetString("cmd_whisper_group_missing_target", resourceCulture);
            }
        }
        
        internal static string cmd_whisper_group_superfluous_target {
            get {
                return ResourceManager.GetString("cmd_whisper_group_superfluous_target", resourceCulture);
            }
        }
        
        internal static string cmd_whisper_list_header {
            get {
                return ResourceManager.GetString("cmd_whisper_list_header", resourceCulture);
            }
        }
        
        internal static string cmd_whisper_list_target_none {
            get {
                return ResourceManager.GetString("cmd_whisper_list_target_none", resourceCulture);
            }
        }
        
        internal static string cmd_whisper_list_target_voice {
            get {
                return ResourceManager.GetString("cmd_whisper_list_target_voice", resourceCulture);
            }
        }
        
        internal static string cmd_whisper_list_target_whispergroup {
            get {
                return ResourceManager.GetString("cmd_whisper_list_target_whispergroup", resourceCulture);
            }
        }
        
        internal static string cmd_whisper_list_target_whisper_channel {
            get {
                return ResourceManager.GetString("cmd_whisper_list_target_whisper_channel", resourceCulture);
            }
        }
        
        internal static string cmd_whisper_list_target_whisper_clients {
            get {
                return ResourceManager.GetString("cmd_whisper_list_target_whisper_clients", resourceCulture);
            }
        }
        
        internal static string error_bot_does_not_exist {
            get {
                return ResourceManager.GetString("error_bot_does_not_exist", resourceCulture);
            }
        }
        
        internal static string error_call_error {
            get {
                return ResourceManager.GetString("error_call_error", resourceCulture);
            }
        }
        
        internal static string error_call_unexpected_error {
            get {
                return ResourceManager.GetString("error_call_unexpected_error", resourceCulture);
            }
        }
        
        internal static string error_cmd_at_least_four_argument {
            get {
                return ResourceManager.GetString("error_cmd_at_least_four_argument", resourceCulture);
            }
        }
        
        internal static string error_cmd_at_least_one_argument {
            get {
                return ResourceManager.GetString("error_cmd_at_least_one_argument", resourceCulture);
            }
        }
        
        internal static string error_cmd_at_least_two_argument {
            get {
                return ResourceManager.GetString("error_cmd_at_least_two_argument", resourceCulture);
            }
        }
        
        internal static string error_could_not_create_bot {
            get {
                return ResourceManager.GetString("error_could_not_create_bot", resourceCulture);
            }
        }
        
        internal static string error_invalid_token_duration {
            get {
                return ResourceManager.GetString("error_invalid_token_duration", resourceCulture);
            }
        }
        
        internal static string error_invoker_not_visible {
            get {
                return ResourceManager.GetString("error_invoker_not_visible", resourceCulture);
            }
        }
        
        internal static string error_missing_session_context {
            get {
                return ResourceManager.GetString("error_missing_session_context", resourceCulture);
            }
        }
        
        internal static string error_nothing_to_return {
            get {
                return ResourceManager.GetString("error_nothing_to_return", resourceCulture);
            }
        }
        
        internal static string error_not_available_from_api {
            get {
                return ResourceManager.GetString("error_not_available_from_api", resourceCulture);
            }
        }
        
        internal static string error_not_found {
            get {
                return ResourceManager.GetString("error_not_found", resourceCulture);
            }
        }
        
        internal static string error_no_active_token {
            get {
                return ResourceManager.GetString("error_no_active_token", resourceCulture);
            }
        }
        
        internal static string error_no_invoker_in_context {
            get {
                return ResourceManager.GetString("error_no_invoker_in_context", resourceCulture);
            }
        }
        
        internal static string error_no_target_channel {
            get {
                return ResourceManager.GetString("error_no_target_channel", resourceCulture);
            }
        }
        
        internal static string error_no_teamspeak_in_context {
            get {
                return ResourceManager.GetString("error_no_teamspeak_in_context", resourceCulture);
            }
        }
        
        internal static string error_no_uid_found {
            get {
                return ResourceManager.GetString("error_no_uid_found", resourceCulture);
            }
        }
        
        internal static string error_playlist_is_empty {
            get {
                return ResourceManager.GetString("error_playlist_is_empty", resourceCulture);
            }
        }
        
        internal static string error_playlist_item_index_out_of_range {
            get {
                return ResourceManager.GetString("error_playlist_item_index_out_of_range", resourceCulture);
            }
        }
        
        internal static string error_playlist_not_found {
            get {
                return ResourceManager.GetString("error_playlist_not_found", resourceCulture);
            }
        }
        
        internal static string error_plugin_error {
            get {
                return ResourceManager.GetString("error_plugin_error", resourceCulture);
            }
        }
        
        internal static string error_unrecognized_descriptor {
            get {
                return ResourceManager.GetString("error_unrecognized_descriptor", resourceCulture);
            }
        }
        
        internal static string error_use_private {
            get {
                return ResourceManager.GetString("error_use_private", resourceCulture);
            }
        }
        
        internal static string info_bot_might_be_unresponsive {
            get {
                return ResourceManager.GetString("info_bot_might_be_unresponsive", resourceCulture);
            }
        }
        
        internal static string info_status_channelcommander {
            get {
                return ResourceManager.GetString("info_status_channelcommander", resourceCulture);
            }
        }
        
        internal static string info_cleanup_done {
            get {
                return ResourceManager.GetString("info_cleanup_done", resourceCulture);
            }
        }
        
        internal static string info_currently_not_playing {
            get {
                return ResourceManager.GetString("info_currently_not_playing", resourceCulture);
            }
        }
        
        internal static string info_currently_playing {
            get {
                return ResourceManager.GetString("info_currently_playing", resourceCulture);
            }
        }
        
        internal static string info_empty {
            get {
                return ResourceManager.GetString("info_empty", resourceCulture);
            }
        }
        
        internal static string info_ok {
            get {
                return ResourceManager.GetString("info_ok", resourceCulture);
            }
        }
        
        internal static string info_quizmode_is_active {
            get {
                return ResourceManager.GetString("info_quizmode_is_active", resourceCulture);
            }
        }
        
        internal static string info_removed {
            get {
                return ResourceManager.GetString("info_removed", resourceCulture);
            }
        }
        
        internal static string info_botstatus_quiztime {
            get {
                return ResourceManager.GetString("info_botstatus_quiztime", resourceCulture);
            }
        }
        
        internal static string info_botstatus_sleeping {
            get {
                return ResourceManager.GetString("info_botstatus_sleeping", resourceCulture);
            }
        }
        
        internal static string cmd_bot_setup_error {
            get {
                return ResourceManager.GetString("cmd_bot_setup_error", resourceCulture);
            }
        }
        
        internal static string error_feature_unavailable {
            get {
                return ResourceManager.GetString("error_feature_unavailable", resourceCulture);
            }
        }
        
        internal static string error_history_could_not_create_entry {
            get {
                return ResourceManager.GetString("error_history_could_not_create_entry", resourceCulture);
            }
        }
        
        internal static string error_history_could_not_find_entry {
            get {
                return ResourceManager.GetString("error_history_could_not_find_entry", resourceCulture);
            }
        }
        
        internal static string error_playlist_broken_file {
            get {
                return ResourceManager.GetString("error_playlist_broken_file", resourceCulture);
            }
        }
        
        internal static string error_ts_cannot_move {
            get {
                return ResourceManager.GetString("error_ts_cannot_move", resourceCulture);
            }
        }
        
        internal static string error_ts_cannot_set_commander {
            get {
                return ResourceManager.GetString("error_ts_cannot_set_commander", resourceCulture);
            }
        }
        
        internal static string error_ts_error {
            get {
                return ResourceManager.GetString("error_ts_error", resourceCulture);
            }
        }
        
        internal static string error_ts_invalid_name {
            get {
                return ResourceManager.GetString("error_ts_invalid_name", resourceCulture);
            }
        }
        
        internal static string error_ts_msg_too_long {
            get {
                return ResourceManager.GetString("error_ts_msg_too_long", resourceCulture);
            }
        }
        
        internal static string error_ts_no_client_found {
            get {
                return ResourceManager.GetString("error_ts_no_client_found", resourceCulture);
            }
        }
        
        internal static string error_ts_unknown_error {
            get {
                return ResourceManager.GetString("error_ts_unknown_error", resourceCulture);
            }
        }
        
        internal static string info_off {
            get {
                return ResourceManager.GetString("info_off", resourceCulture);
            }
        }
        
        internal static string info_on {
            get {
                return ResourceManager.GetString("info_on", resourceCulture);
            }
        }
        
        internal static string info_status_quizmode {
            get {
                return ResourceManager.GetString("info_status_quizmode", resourceCulture);
            }
        }
        
        internal static string info_status_random {
            get {
                return ResourceManager.GetString("info_status_random", resourceCulture);
            }
        }
        
        internal static string error_config_value_parse_error {
            get {
                return ResourceManager.GetString("error_config_value_parse_error", resourceCulture);
            }
        }
        
        internal static string error_io_in_use {
            get {
                return ResourceManager.GetString("error_io_in_use", resourceCulture);
            }
        }
        
        internal static string error_io_missing_permission {
            get {
                return ResourceManager.GetString("error_io_missing_permission", resourceCulture);
            }
        }
        
        internal static string error_io_unknown_error {
            get {
                return ResourceManager.GetString("error_io_unknown_error", resourceCulture);
            }
        }
        
        internal static string error_media_failed_to_parse_id {
            get {
                return ResourceManager.GetString("error_media_failed_to_parse_id", resourceCulture);
            }
        }
        
        internal static string error_media_file_not_found {
            get {
                return ResourceManager.GetString("error_media_file_not_found", resourceCulture);
            }
        }
        
        internal static string error_media_image_not_found {
            get {
                return ResourceManager.GetString("error_media_image_not_found", resourceCulture);
            }
        }
        
        internal static string error_media_internal_invalid {
            get {
                return ResourceManager.GetString("error_media_internal_invalid", resourceCulture);
            }
        }
        
        internal static string error_media_internal_missing {
            get {
                return ResourceManager.GetString("error_media_internal_missing", resourceCulture);
            }
        }
        
        internal static string error_media_invalid_image {
            get {
                return ResourceManager.GetString("error_media_invalid_image", resourceCulture);
            }
        }
        
        internal static string error_media_invalid_uri {
            get {
                return ResourceManager.GetString("error_media_invalid_uri", resourceCulture);
            }
        }
        
        internal static string error_media_no_stream_extracted {
            get {
                return ResourceManager.GetString("error_media_no_stream_extracted", resourceCulture);
            }
        }
        
        internal static string error_net_empty_response {
            get {
                return ResourceManager.GetString("error_net_empty_response", resourceCulture);
            }
        }
        
        internal static string error_net_error_status_code {
            get {
                return ResourceManager.GetString("error_net_error_status_code", resourceCulture);
            }
        }
        
        internal static string error_net_no_connection {
            get {
                return ResourceManager.GetString("error_net_no_connection", resourceCulture);
            }
        }
        
        internal static string error_net_timeout {
            get {
                return ResourceManager.GetString("error_net_timeout", resourceCulture);
            }
        }
        
        internal static string error_net_unknown {
            get {
                return ResourceManager.GetString("error_net_unknown", resourceCulture);
            }
        }
        
        internal static string error_playlist_cannot_access_not_owned {
            get {
                return ResourceManager.GetString("error_playlist_cannot_access_not_owned", resourceCulture);
            }
        }
        
        internal static string error_playlist_name_invalid_character {
            get {
                return ResourceManager.GetString("error_playlist_name_invalid_character", resourceCulture);
            }
        }
        
        internal static string error_playlist_name_invalid_empty {
            get {
                return ResourceManager.GetString("error_playlist_name_invalid_empty", resourceCulture);
            }
        }
        
        internal static string error_playlist_name_invalid_too_long {
            get {
                return ResourceManager.GetString("error_playlist_name_invalid_too_long", resourceCulture);
            }
        }
        
        internal static string error_playlist_no_store_directory {
            get {
                return ResourceManager.GetString("error_playlist_no_store_directory", resourceCulture);
            }
        }
        
        internal static string error_playlist_special_not_found {
            get {
                return ResourceManager.GetString("error_playlist_special_not_found", resourceCulture);
            }
        }
        
        internal static string error_playmgr_internal_error {
            get {
                return ResourceManager.GetString("error_playmgr_internal_error", resourceCulture);
            }
        }
        
        internal static string error_playmgr_many_songs_failed {
            get {
                return ResourceManager.GetString("error_playmgr_many_songs_failed", resourceCulture);
            }
        }
        
        internal static string error_resfac_could_not_load {
            get {
                return ResourceManager.GetString("error_resfac_could_not_load", resourceCulture);
            }
        }
        
        internal static string error_resfac_multiple_factories_failed {
            get {
                return ResourceManager.GetString("error_resfac_multiple_factories_failed", resourceCulture);
            }
        }
        
        internal static string error_resfac_no_registered_factory {
            get {
                return ResourceManager.GetString("error_resfac_no_registered_factory", resourceCulture);
            }
        }
        
        internal static string error_ytdl_empty_response {
            get {
                return ResourceManager.GetString("error_ytdl_empty_response", resourceCulture);
            }
        }
        
        internal static string error_ytdl_failed_to_run {
            get {
                return ResourceManager.GetString("error_ytdl_failed_to_run", resourceCulture);
            }
        }
        
        internal static string error_ytdl_not_found {
            get {
                return ResourceManager.GetString("error_ytdl_not_found", resourceCulture);
            }
        }
        
        internal static string error_ytdl_song_failed_to_load {
            get {
                return ResourceManager.GetString("error_ytdl_song_failed_to_load", resourceCulture);
            }
        }
        
        internal static string info_playmgr_no_next_song {
            get {
                return ResourceManager.GetString("info_playmgr_no_next_song", resourceCulture);
            }
        }
        
        internal static string info_playmgr_no_previous_song {
            get {
                return ResourceManager.GetString("info_playmgr_no_previous_song", resourceCulture);
            }
        }
        
        internal static string error_no_help {
            get {
                return ResourceManager.GetString("error_no_help", resourceCulture);
            }
        }
        
        internal static string error_no_session_in_context {
            get {
                return ResourceManager.GetString("error_no_session_in_context", resourceCulture);
            }
        }
        
        internal static string error_ts_code_2568 {
            get {
                return ResourceManager.GetString("error_ts_code_2568", resourceCulture);
            }
        }
        
        internal static string cmd_bot_connect_to_help {
            get {
                return ResourceManager.GetString("cmd_bot_connect_to_help", resourceCulture);
            }
        }
        
        internal static string cmd_bot_connect_template_help {
            get {
                return ResourceManager.GetString("cmd_bot_connect_template_help", resourceCulture);
            }
        }
        
        internal static string cmd_bot_save_help {
            get {
                return ResourceManager.GetString("cmd_bot_save_help", resourceCulture);
            }
        }
        
        internal static string cmd_history_clean_removedefective_help {
            get {
                return ResourceManager.GetString("cmd_history_clean_removedefective_help", resourceCulture);
            }
        }
        
        internal static string cmd_if_help {
            get {
                return ResourceManager.GetString("cmd_if_help", resourceCulture);
            }
        }
        
        internal static string cmd_settings_get_help {
            get {
                return ResourceManager.GetString("cmd_settings_get_help", resourceCulture);
            }
        }
        
        internal static string cmd_settings_global_get_help {
            get {
                return ResourceManager.GetString("cmd_settings_global_get_help", resourceCulture);
            }
        }
        
        internal static string cmd_settings_global_set_help {
            get {
                return ResourceManager.GetString("cmd_settings_global_set_help", resourceCulture);
            }
        }
        
        internal static string cmd_settings_help {
            get {
                return ResourceManager.GetString("cmd_settings_help", resourceCulture);
            }
        }
        
        internal static string cmd_settings_help_help {
            get {
                return ResourceManager.GetString("cmd_settings_help_help", resourceCulture);
            }
        }
        
        internal static string cmd_settings_set_help {
            get {
                return ResourceManager.GetString("cmd_settings_set_help", resourceCulture);
            }
        }
        
        internal static string _undocumented {
            get {
                return ResourceManager.GetString("_undocumented", resourceCulture);
            }
        }
        
        internal static string cmd_bot_avatar_set_help {
            get {
                return ResourceManager.GetString("cmd_bot_avatar_set_help", resourceCulture);
            }
        }
        
        internal static string cmd_song_position_help {
            get {
                return ResourceManager.GetString("cmd_song_position_help", resourceCulture);
            }
        }
        
        internal static string error_missing_right {
            get {
                return ResourceManager.GetString("error_missing_right", resourceCulture);
            }
        }
        
        internal static string cmd_repeat_all_help {
            get {
                return ResourceManager.GetString("cmd_repeat_all_help", resourceCulture);
            }
        }
        
        internal static string cmd_repeat_info_all {
            get {
                return ResourceManager.GetString("cmd_repeat_info_all", resourceCulture);
            }
        }
        
        internal static string cmd_repeat_info_off {
            get {
                return ResourceManager.GetString("cmd_repeat_info_off", resourceCulture);
            }
        }
        
        internal static string cmd_repeat_info_one {
            get {
                return ResourceManager.GetString("cmd_repeat_info_one", resourceCulture);
            }
        }
        
        internal static string cmd_bot_avatar_clear_help {
            get {
                return ResourceManager.GetString("cmd_bot_avatar_clear_help", resourceCulture);
            }
        }
        
        internal static string error_cmd_could_not_convert_to {
            get {
                return ResourceManager.GetString("error_cmd_could_not_convert_to", resourceCulture);
            }
        }
        
        internal static string error_cmd_no_matching_overload {
            get {
                return ResourceManager.GetString("error_cmd_no_matching_overload", resourceCulture);
            }
        }
        
        internal static string error_cmd_number_too_big {
            get {
                return ResourceManager.GetString("error_cmd_number_too_big", resourceCulture);
            }
        }
        
        internal static string error_cmd_at_least_n_arguments {
            get {
                return ResourceManager.GetString("error_cmd_at_least_n_arguments", resourceCulture);
            }
        }
        
        internal static string error_cmd_at_least_three_argument {
            get {
                return ResourceManager.GetString("error_cmd_at_least_three_argument", resourceCulture);
            }
        }
        
        internal static string cmd_bot_description_set_help {
            get {
                return ResourceManager.GetString("cmd_bot_description_set_help", resourceCulture);
            }
        }
        
        internal static string cmd_settings_bot_reload_help {
            get {
                return ResourceManager.GetString("cmd_settings_bot_reload_help", resourceCulture);
            }
        }
        
        internal static string cmd_settings_create_help {
            get {
                return ResourceManager.GetString("cmd_settings_create_help", resourceCulture);
            }
        }
        
        internal static string cmd_settings_delete_help {
            get {
                return ResourceManager.GetString("cmd_settings_delete_help", resourceCulture);
            }
        }
        
        internal static string cmd_settings_reload_help {
            get {
                return ResourceManager.GetString("cmd_settings_reload_help", resourceCulture);
            }
        }
        
        internal static string cmd_settings_copy_help {
            get {
                return ResourceManager.GetString("cmd_settings_copy_help", resourceCulture);
            }
        }
        
        internal static string cmd_queue_help {
            get {
                return ResourceManager.GetString("cmd_queue_help", resourceCulture);
            }
        }
        
        internal static string cmd_info_help {
            get {
                return ResourceManager.GetString("cmd_info_help", resourceCulture);
            }
        }
        
        internal static string cmd_list_item_name_help {
            get {
                return ResourceManager.GetString("cmd_list_item_name_help", resourceCulture);
            }
        }
        
        internal static string error_cmd_complexity_reached {
            get {
                return ResourceManager.GetString("error_cmd_complexity_reached", resourceCulture);
            }
        }
        
        internal static string cmd_alias_add_help {
            get {
                return ResourceManager.GetString("cmd_alias_add_help", resourceCulture);
            }
        }
        
        internal static string cmd_alias_list_help {
            get {
                return ResourceManager.GetString("cmd_alias_list_help", resourceCulture);
            }
        }
        
        internal static string cmd_alias_remove_help {
            get {
                return ResourceManager.GetString("cmd_alias_remove_help", resourceCulture);
            }
        }
        
        internal static string cmd_alias_show_help {
            get {
                return ResourceManager.GetString("cmd_alias_show_help", resourceCulture);
            }
        }
        
        internal static string cmd_pm_user_help {
            get {
                return ResourceManager.GetString("cmd_pm_user_help", resourceCulture);
            }
        }
        
        internal static string cmd_search_header {
            get {
                return ResourceManager.GetString("cmd_search_header", resourceCulture);
            }
        }
        
        internal static string cmd_search_no_result {
            get {
                return ResourceManager.GetString("cmd_search_no_result", resourceCulture);
            }
        }
        
        internal static string error_select_empty {
            get {
                return ResourceManager.GetString("error_select_empty", resourceCulture);
            }
        }
        
        internal static string error_value_not_in_range {
            get {
                return ResourceManager.GetString("error_value_not_in_range", resourceCulture);
            }
        }
        
        internal static string info_number {
            get {
                return ResourceManager.GetString("info_number", resourceCulture);
            }
        }
        
        internal static string cmd_select_help {
            get {
                return ResourceManager.GetString("cmd_select_help", resourceCulture);
            }
        }
        
        internal static string error_ts_file_too_big {
            get {
                return ResourceManager.GetString("error_ts_file_too_big", resourceCulture);
            }
        }
        
        internal static string error_ts_code_781 {
            get {
                return ResourceManager.GetString("error_ts_code_781", resourceCulture);
            }
        }
        
        internal static string login_to_spotify_using_this_url {
            get {
                return ResourceManager.GetString("login_to_spotify_using_this_url", resourceCulture);
            }
        }
        
        internal static string copy_redirect_url_here {
            get {
                return ResourceManager.GetString("copy_redirect_url_here", resourceCulture);
            }
        }
    }
}
